# Generated by Django 3.1.2 on 2020-10-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201027_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'Red'), ('bg-light', 'White'), ('bg-info', 'Blue'), ('bg-success', 'Green')], default='bg-light', max_length=20),
        ),
    ]
