# Generated by Django 3.1.2 on 2020-10-29 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_auto_20201027_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('bg-danger', 'Red'), ('bg-light', 'White'), ('bg-info', 'Blue'), ('bg-success', 'Green')], default='bg-light', max_length=20)),
                ('pin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.todonote')),
            ],
        ),
    ]
