# Generated by Django 3.1.2 on 2020-11-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_todo_todonote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed', '-pk']},
        ),
    ]
